### ISSUE TITLE
Changing the Unit_of_measurement does not change the sensor value

### ISSUE THREAD

**Issue by ChristophCaina** [skodaconnect/homeassistant-skodaconnect#189]
Hi,

The unit change itself does work, but the sensor value will not be changed... :-(
![grafik](https://user-images.githubusercontent.com/26391061/227714854-8fa068e0-9fd3-4092-8a48-14a63fa30df1.png)

it shows "5000 kW" instead of 5 kW
the value remains the same while changing between W and kW
Not sure, why this happens, but it seems a bit strange to me, because I thought, HA should handle how the value will be displayed...

_Originally posted by @ChristophCaina in https://github.com/lendy007/homeassistant-skodaconnect/issues/185#issuecomment-1483800621_

**Comment by Farfar** [comment]
The changes needed for the native conversion to work is a bit sparse imho. But also this integration isn't that well maintained anymore since I haven't had time to keep up with HA development.

With that said I think I know what needs changing in code and I'll try to find some time to make it work.

**Comment by dvx76** [comment]
I had another look at https://developers.home-assistant.io/blog/2022/12/07/unit_system_changes/ and I don't think it does what we've been assuming here.

This is not to handle automatic conversion from, say, m to km or w to kw, but just changing the unit_of_measurement in the sensor. Instead my understanding is that it is for automatic conversion from metric to imperial and back, based on the Unit System selected under Settings -> General. The device classes covered at `distance, gas, precipitation, precipitation_intensity, speed, volume, water, weight, or wind_speed`, not for example `power`, the device class of `charging_power` sensor.

Let me know if you have a different explanation.
