### ISSUE TITLE
Charging time left is always showing whole hours

### ISSUE THREAD

**Issue by haraldpaulsen** [skodaconnect/homeassistant-skodaconnect#195]
A few updates ago I noticed that charging time left always shows a whole amount of hours. This might have changed during home assistant introducing rounding etc. Is anyone else having the same problem?

Running lastest HaOS, hacs and this integration. 

![Screenshot_20230530_095116_Chrome](https://github.com/lendy007/homeassistant-skodaconnect/assets/25634252/22d2fe63-01cc-4934-938c-fba8289e23a1)

Skoda citigo.

Will get debug logs later if it is just me

**Comment by dvx76** [comment]
Yep, someone reported the same problem on Discord. I also think it's related to an HA update.

**Comment by haraldpaulsen** [comment]
If I go to developer tools / states, I can see that it has more granularity.
Current state: 00:25
Attributes:

```
state_class: measurement
model: Škoda CitigoE iV Style/2019-12-05
unit_of_measurement: h
assumed_state: true
device_class: duration
icon: mdi:battery-charging-100
friendly_name: Oda Charging time left
```

So the data is there, but it is just displayed wrong? Or are we using the incorrect device_class or something else?

As a work around, maybe it could be converted to minutes for display in my dashboard. Will have to test later when the car is charging again.

**Comment by haraldpaulsen** [comment]
Made some progress doing research.
If unit_of_measurement is "h", the value should be hours in decimal format, like 1.5. That would show like 01:30:00. Otherwise Home Assistant will do some parsing and only use the first number. This appears to be a special handling if the unit is "h". Something else would display the whole value/state.

What is the format we get from the Skoda API?

**Comment by dvx76** [comment]
So the API returns either seconds or minutes (depends on the vehicle). But then we convert this into a `hh:mm` string. I can only guess this was nice before HA introduced the concept of `unit_of_measurement` and `device_class`.

I tested with just returning the minutes as an int and changing `unit_of_measurement = min`. If works fine for the Entities and Mushroom Entity card but for some reason the Entity card (one entity) just shows the raw value with the unit of `min` ...

I guess if we change this we'd want to also update all other durations (like clima time left).
 
![image](https://github.com/Farfar/homeassistant-skodaconnect/assets/785424/3ff7b34a-2d73-447f-980f-72727101319a)

**Comment by haraldpaulsen** [comment]
I agree, returning it as minutes would be a good option!
