### ISSUE TITLE
Sign in via HA doesn't work

### ISSUE THREAD

**Issue by michaldobrotka** [skodaconnect/homeassistant-skodaconnect#198]
Hi guys, I'm trying to sing in via integration, but it doesn't work for me. Skoda connect App via browser or mobile forks fine. Is there currently any issue?
Thanks

**Comment by dvx76** [comment]
Have you reviewed [this section](https://github.com/skodaconnect/homeassistant-skodaconnect#if-you-encounter-problems) in the readme?

> If you encounter a problem where the integration can't be setup or if you receive an error that there's unaccepted terms or eula, it might be because of your mobile app platform. The underlying library is built by reverse engineering the Android App behavious and thus it use the same client configurations as an Adnroid device. If you only use the app on iPhone/iOS devices it might cause issues with this integration. A workaround is to open the MySkoda app on an android device and it should present an EULA or new terms and condititions to be accepted. If this does not work for you and the particular problem you are facing, please open an issue and provide as detailed problem description as possible and relevant debug logs.

**Comment by matrevis** [comment]
Seems that all the vw services (VW, Skoda and Seat/Cupra) are having problems logging in and no eula or terms and conditions to accept. From app you can access regularly.

**Comment by michaldobrotka** [comment]
Yeas, I tried it Yesterday one more time, reinstalled mobile app too, but no message to accept in app by attempt to login in HA

**Comment by strandlie** [comment]
I can confirm that I also experience this issue. The logs give this error message, 

Missing consent for client "technical" scopes: profile

To me this indicates some missing consent/EULA etc, but nothing shows up in neither the iOS nor Android app upon login.

**Comment by iamslan** [comment]
@strandlie @michaldobrotka @matrevis Just login on the "old" application "MySkoda essentials", not the new "MySkoda", and then it will work in HA!

**Comment by strandlie** [comment]
Fantastic, that works. Thanks. 

I feel like that should be in the documentation somewhere.

**Comment by michaldobrotka** [comment]
Thanks @iamslan , works for me too!!

**Comment by michaldobrotka** [comment]
Partial Solution is to use older app Skoda Essentials - solved for now :)
