### ISSUE TITLE
Login Problem with Seat Connect

### ISSUE THREAD

**Issue by metcrl** [skodaconnect/homeassistant-skodaconnect#200]
Hello,
Since this morning the Seat Connect integration don't work.
I try to write here because the Seat fork has not been updated for a very long time. Newbie question, isn't it possible to make sure to continue the development in parallel?
I tried to reconfigure all, but i can't even access anymore.
When I insert my login mail/password, the screen with rounding circle "access to Seat Connect" apper and nothing happen

This is the problem, delete all and reinstall didn't work:
![Senza titolo-1](https://github.com/skodaconnect/homeassistant-skodaconnect/assets/70216900/f60b6012-14de-4575-bd01-081470b6bdb0)

**Comment by kjbstar** [comment]
Hey there, 

same issue here on this very integration (Skoda), after a restart of HA.

Logs are very clear, even if I have no idea how to do what is asks :)

> Cette erreur provient d'une intégration personnalisée

Logger: skodaconnect.connection
Source: custom_components/skodaconnect/__init__.py:896
Integration: Skoda Connect (documentation, issues)
First occurred: 14:58:55 (8 occurrences)
Last logged: 15:04:20

The terms and conditions must be accepted first at "https://www.skoda-connect.com/"

**Comment by Farfar** [comment]
> Hello, Since this morning the Seat Connect integration don't work. I try to write here because the Seat fork has not been updated for a very long time. Newbie question, isn't it possible to make sure to continue the development in parallel? I tried to reconfigure all, but i can't even access anymore. When I insert my login mail/password, the screen with rounding circle "access to Seat Connect" apper and nothing happen
> 
> This is the problem, delete all and reinstall didn't work: ![Senza titolo-1](https://user-images.githubusercontent.com/70216900/249854417-f60b6012-14de-4575-bd01-081470b6bdb0.jpg)

It sure is. Problem is someone with access need to make an effort to update it. I don't have a Seat, never did, and as of now I don't have time to code anything.

**Comment by dvx76** [comment]
I think this was resolved recently after some discussions on discord?

If not I would suggest to report the issue in https://github.com/Farfar/homeassistant-seatconnect
