### ISSUE TITLE
png not shown

### ISSUE THREAD

**Issue by riddertommie** [skodaconnect/homeassistant-skodaconnect#201]
**Describe the bug**
both Model image not shown (small or large), if i puth them on a dashboard (i select everything related to my car and only these 2 wont work/show)

**Is this working in MySkoda app?***
Image are shown in app

**Latest working release**
Did not work as long as i known, working with 1.2.5? no Beta

**Debug logs**

![image](https://github.com/skodaconnect/homeassistant-skodaconnect/assets/3483150/512bee13-c5b6-4141-b171-2c3949689372)

**Installation:**
 - Home Assistant variant: [e.g. Hass OS, Docker, Core, Supervised] 
 Docker
 - Python version [e.g. 3.7, 3.8]
 Python 3.11.4 (main, Jun 22 2023, 19:40:35) [GCC 12.2.1 20220924] on linux
 - Python library versions ["python3 -m pip list"]
 python-blockchain-api            0.0.2
python-bsblan                    0.5.11
python-clementine-remote         1.0.1
python-dateutil                  2.8.2
python-didl-lite                 1.3.2
python-digitalocean              1.13.2
python-ecobee-api                0.2.14
python-engineio                  3.14.2
python-etherscan-api             0.0.3
python-family-hub-local          0.0.2
python-fullykiosk                0.0.12
python-gc100                     1.0.3a0
python-gitlab                    1.6.0
python-homewizard-energy         2.0.1
python-hpilo                     4.3
python-http-client               3.3.7
python-izone                     1.2.9
python-join-api                  0.0.9
python-jose                      3.3.0
python-juicenet                  1.1.0
python-jwt                       4.0.0
python-kasa                      0.5.2
python-magic                     0.4.27
python-matter-server             3.6.3
python-miio                      0.5.12
python-mpd2                      3.0.5
python-mystrom                   2.2.0
python-nest                      4.2.0
python-opendata-transport        0.3.0
python-opensky                   0.0.10
python-otbr-api                  2.2.0
python-picnic-api                1.1.0
python-qbittorrent               0.4.3
python-ripple-api                0.0.3
python-roborock                  0.30.0
python-slugify                   4.0.1
python-smarttub                  0.0.33
python-socketio                  4.6.1
python-songpal                   0.15.2
python-tado                      0.15.0
python-telegram-bot              13.1
python-vlc                       1.1.2

**Additional context**

If i copy the url directly to the  browser i see the images, see below example

https://ip-modcwp.azureedge.net/modcwp5azs22101014/2Y2Yst_L3HCJwzxo7X5l-2NpAxfdMTFtKr98.Xmjva4Qh-8GrXNPj39ZSVlh2K-93FmIcq6jebJxsP1puUERC7Oh0.-B-1080570dayvext_front1080.png

**Comment by Farfar** [comment]
The url is just that, a url. It's not a picture.
The sensor is working as intended.
