### ISSUE TITLE
Cannot login to the HA skoda connect intergration.

### ISSUE THREAD

**Issue by shoarma4life** [skodaconnect/homeassistant-skodaconnect#204]
**Describe the bug**
I cannot login to the skodaconnect intergration in homeassistant. Its says:
**Could not log in to Skoda Connect, check your details and check if the service is working**.

**Is this working in MySkoda app?***
The App is working fine on Android 13. Its the officail MySkoda app.

Logout and login in the MySkoda app, preferably on Android.
Done, no change.

Make sure that you have the latest app updates, sometimes there's new consent needed that will only show in latest app version.
App is laters version, same applies voor the homeassistant-skodaconnect 

**Latest working release**
If the problem started after updating to a new release, please state latest working release.
Not been working before.

**Debug logs**
Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.skodaconnect.config_flow
Source: custom_components/skodaconnect/config_flow.py:103
Integration: skodaconnect (documentation, issues)
First occurred: 15 augustus 2023 om 22:30:48 (6 occurrences)
Last logged: 10:32:17

Login failed with error: Missing consent for client "technical" scopes: profile

**Installation:**
Home Assistant 2023.8.2
Supervisor 2023.08.1
Operating System 10.4
Frontend-versie: 20230802.0 - latest
Running in vmware esx  8 virtual server.

**Additional context**
I have the car only 2 days. The certificate on the myskoda page is generated.

**Comment by Farfar** [comment]
> **Describe the bug** I cannot login to the skodaconnect intergration in homeassistant. Its says: **Could not log in to Skoda Connect, check your details and check if the service is working**.
> 
> **Is this working in MySkoda app?*** The App is working fine on Android 13. Its the officail MySkoda app.
> 
> Logout and login in the MySkoda app, preferably on Android. Done, no change.
> 
> Make sure that you have the latest app updates, sometimes there's new consent needed that will only show in latest app version. App is laters version, same applies voor the homeassistant-skodaconnect
> 
> **Latest working release** If the problem started after updating to a new release, please state latest working release. Not been working before.
> 
> **Debug logs** Deze fout is ontstaan door een aangepaste integratie.
> 
> Logger: custom_components.skodaconnect.config_flow Source: custom_components/skodaconnect/config_flow.py:103 Integration: skodaconnect (documentation, issues) First occurred: 15 augustus 2023 om 22:30:48 (6 occurrences) Last logged: 10:32:17
> 
> Login failed with error: Missing consent for client "technical" scopes: profile
> 
> **Installation:** Home Assistant 2023.8.2 Supervisor 2023.08.1 Operating System 10.4 Frontend-versie: 20230802.0 - latest Running in vmware esx 8 virtual server.
> 
> **Additional context** I have the car only 2 days. The certificate on the myskoda page is generated.

Please install the MySkoda Essentials app and login to that prior to trying the integration again.

The integration is based on the old MySkoda app but then they split the app and communications into two apps and we haven't had time to implement changes for this.

**Comment by shoarma4life** [comment]
Thank you so much! It's worked straight away after I logged in the essentials app.
