### ISSUE TITLE
Improve GPS position accuracy

### ISSUE THREAD

**Issue by NickSutton** [skodaconnect/homeassistant-skodaconnect#209]
**Is your feature request related to a problem? Please describe.**
The car's GPS position is reported as an attribute within the device.tracker entity that this integration creates, however the lat and lon is only reported to 2 decimal places. 

**Describe the solution you'd like**
Report the lat and lon to 5 decimal places

**Comment by dvx76** [comment]
Which car is this? I'm getting 6 decimals here so possibly limited by what is being returned by  the server for your car?

```
source_type: gps
latitude: 55.062878
longitude: 7.631352
gps_accuracy: 0
model: Škoda Enyaq 80 iV 80/2022-07-01
entity_picture: https://ip-modcwp.azureedge.net/modcwp5azs22200218/8X8XdPgci_nZToLW-5ULF6ayj.sgCneqdDwt0-QxJv4obND1itVKA7q5X.UlSY-li0Lfv2.O4_SdInzqCbaYBos8Ww-B-700390dayvext_front1080.png
assumed_state: true
icon: mdi:car
friendly_name: Skoda Enyaq Position
```

**Comment by WebSpider** [comment]
This could be related to the unit/measurement/rounding settings that HA has for the sensor.
