### ISSUE TITLE
Connection unavailable every evening about 6...8 pm?

### ISSUE THREAD

**Issue by andreasengelsberg** [skodaconnect/homeassistant-skodaconnect#210]
I recently observed, that the connection status changes to unavailable every evening about 6...8 pm. It changes to available again about 2 am. In case of unavailabilty also the Skoda APP reports unavailabilty of vehicle data. See screenshot of one entity ("white areas" mark periods of anavailabilty):
![grafik](https://github.com/skodaconnect/homeassistant-skodaconnect/assets/133257655/665fe308-784a-48c7-8b4e-a42b4e0c5a01)

Does anyone observe the same behaviour and has hints for changing the behaviour (maybe configuration topic)?

Thank you very much

**Comment by WebSpider** [comment]
We've received reports about this, and it seems to be related to restrictions being imposed by VAG on how often you can poll data.
As a workaround, you could try increasing the polling interval

**Comment by andreasengelsberg** [comment]
Thank you very much for the reply. Now I have changed the polling interval from 60s to 90s and will check, if the behaviour is different. Btw. is there any mechanism to initate polling of data by automation e.g. in case of starting charging by HA?

**Comment by WebSpider** [comment]
There currently is not, but this would be a great feature request!

**Comment by dvx76** [comment]
So weird. I'm not having these issues at all ...
Poll frequency = 30 (seconds)

![image](https://github.com/skodaconnect/homeassistant-skodaconnect/assets/785424/430bedf7-a9c8-4669-a5ac-4b6c9c41bc99)

**Comment by Farfar** [comment]
I believe this issue is isolated to the old API which is why Enyaq owners won't be affected.

**Comment by andreasengelsberg** [comment]
Update: After changing the polling interval from 60s to 90s there was no period of unavailability last night!
Thank you very much.
