### ISSUE TITLE
Units (km vs imperial)

### ISSUE THREAD

**Issue by dpawson** [skodaconnect/homeassistant-skodaconnect#216]
**Describe the bug**

Electric range 42 km
yet
Select distance/unit conversions.
No conversion
Imperial units

**Is this working in MySkoda app?***
Logout and login in the MySkoda app, preferably on Android.
Make sure that you have the latest app updates, sometimes there's new consent needed that will only show in latest app version.

Not available in app. 

**Latest working release**
If the problem started after updating to a new release, please state latest working release.

App: 5.61 build 2002276111
ha-skodaconnect newly installed (today)

**Debug logs**
If applicable, add debug logs. See [README](https://github.com/lendy007/homeassistant-skodaconnect#enable-debug-logging) on how to enable debug logs with response debugging.

N/A - just conversion?

**Installation:**
 - Home Assistant variant: [e.g. Hass OS, Docker, Core, Supervised] hass
 - Python version [e.g. 3.7, 3.8]  Python 3.11.5 
 - Python library versions ["python3 -m pip list"]
  which ones?
google-auth-oauthlib         1.0.0
html5lib                     1.1
importlib-resources          6.0.0
libclang                     16.0.0
libcomps                     0.1.20
matplotlib                   3.7.3
matplotlib-inline            0.1.6
oauthlib                     3.2.2
requests-oauthlib            1.3.1
sgmllib3k                    1.0.0
urllib3                      1.26.16

**Additional context**

New to this integration. Good Python experience, 2 years with HA (user, not dev)

**Comment by dvx76** [comment]
Could you provide a bit more detail about what you're trying to do? Maybe with an example.

What is your HA Unit System set to? (Settings -> General)

**Comment by dpawson** [comment]
Units set to metric.
Would like to see the readings as requested?

**Comment by dvx76** [comment]
I'm sorry but it's still not clear to me.

I have Unit System set to metric and I'm seeing sensors, like the range, reported in metric.

Can you please provide the exact output or a screenshot of what you are seeing and what you would expect to see instead?
