### ISSUE TITLE
Detect connection problems to api

### ISSUE THREAD

**Issue by spali** [skodaconnect/homeassistant-skodaconnect#218]
Today and partially still are connection problems to skoda connect. It's not a Problem with the integration.
But I couldn't find a way to detect this except in the logs. All sensors are available. 
Did I overlook something or would it be possible to have a sensor made unavailable when update fails due server problem's? 
The use case is, that automations don't run on outdated informations.

**Comment by dvx76** [comment]
Hi, can you copy/paste the errors you're seeing in the logs.

When I intentionally break one of the API endpoints from where data is fetched the related sensors become unavailable.

What happens quite often for me is that pulling data from the Skoda API is still working fine but sending requests (start/stop charge, heating, etc) fails.

**Comment by spali** [comment]
I'm sorry have no logs saved of the event.
I first detected the problem, as the official app didn't even login. After a while I could login, but no car. And then after a couple hours it worked again.
During the time it didn't work, the sensors just showed the last value. Maybe it wasn't completely unavailable or some weird state in between ;)
If this was maybe an edge case and usually they show as unavailable, I'm fine if you close this issue.
