### ISSUE TITLE
preheater return error 2

### ISSUE THREAD

**Issue by sodd** [skodaconnect/homeassistant-skodaconnect#236]
**Describe the bug**
First of all, thx for this repository and hard work, rly appreciate it!
I have truble to start setPreHeater function. When I start this function, API return me error 2. 

**Is this working in MySkoda app?***
Yes, but this functionality is called Auxiliary Heater and I'm little confuse about that.

**Latest working release**
-

**Debug logs**
[paste service](https://paste.kodi.tv/asuhihodac.kodi)

**Installation:**
 - Home Assistant variant: Hass OS
 - Python version 3.11
 - Python library versions 1.2.7

**Additional context**
I'm not sure if I get this functionally get right, coz all I want is to start car heater from HA and straight through was to call `*_parking_heater_heating`  switch to ON, but error 2 occur appears.

**Comment by msandvold** [comment]
https://github.com/skodaconnect/homeassistant-skodaconnect/issues/188

**Comment by sodd** [comment]
> Related to this? #188

Thx for replay, but I don't know, because even if I send "new" heat time duration and then send switch on at *_parking_heater_heating nothing change. Or mby I'm doing it all wrong and I should send *_parking_heater_ventilation instead of *_parking_heater_heating?

**Comment by msandvold** [comment]
@sodd
I think you need to have the payed for version of "Care Connect"
I have setup as mentioned in #188.
Working fine, as long as Skoda servers are "online".

**Comment by dvx76** [comment]
@sodd did you get this working? I don't have a car with parking heater so I can't test this. I'm not seeing either `*_parking_heater_ventilation` or `*_parking_heater_heating` in the example updated in #205 . Where does that come from? If this isn't working for you we'll need debug logs from the integration.
