### ISSUE TITLE
Trying to add car gives error on login

### ISSUE THREAD

**Issue by kekonn** [skodaconnect/homeassistant-skodaconnect#237]
**Describe the bug**
When I try to add my car I get an error after entering my credentials, My logs contain the following error:
`Login failed with error: Token exchange failed. Request status: 410`
 Source: custom_components/skodaconnect/config_flow.py:103 

**Is this working in MySkoda app?***
Logout and login in the MySkoda app, preferably on Android.
Make sure that you have the latest app updates, sometimes there's new consent needed that will only show in latest app version.
Yes, but the app has recently updated an 410 means gone? Perhaps the API has updated it's urls?

**Latest working release**
It was working this morning on the current release (1.2.7)

**Debug logs**
```
2023-12-11 15:40:06.239 ERROR (MainThread) [skodaconnect.connection] Token exchange failed. Request status: 410
2023-12-11 15:40:06.240 ERROR (MainThread) [custom_components.skodaconnect.config_flow] Login failed with error: Token exchange failed. Request status: 410
```

**Installation:**
 - Home Assistant variant: Hass OS
 - Python version: Whatever the latest Hass OS uses
 - Python library versions
 
 ```
Package            Version
------------------ ----------
aioesphomeapi      15.0.0
ajsonrpc           1.2.0
anyio              4.0.0
async-timeout      4.0.3
bitarray           2.8.2
bitstring          4.1.2
bottle             0.12.25
certifi            2023.7.22
cffi               1.16.0
charset-normalizer 3.3.2
click              8.1.7
colorama           0.4.6
cryptography       41.0.5
ecdsa              0.18.0
esphome            2023.10.6
esphome-dashboard  20230904.0
esptool            4.6.2
h11                0.14.0
idna               3.4
ifaddr             0.2.0
kconfiglib         13.7.1
marshmallow        3.20.1
noiseprotocol      0.3.1
packaging          23.2
paho-mqtt          1.6.1
pathspec           0.11.2
pip                23.3.1
platformio         6.1.11
protobuf           4.25.0
pycparser          2.21
pyelftools         0.29
pyparsing          3.1.1
pyserial           3.5
PyYAML             6.0.1
reedsolo           1.7.0
requests           2.31.0
semantic-version   2.10.0
setuptools         68.2.2
six                1.16.0
sniffio            1.3.0
starlette          0.31.1
tabulate           0.9.0
tornado            6.3.3
tzdata             2023.3
tzlocal            5.0.1
urllib3            2.0.7
uvicorn            0.23.2
voluptuous         0.13.1
wheel              0.41.3
wsproto            1.2.0
yamllint           1.33.0
zeroconf           0.115.1
```

**Additional context**
I got an update to the app either today or yesterday. The app is still working, so I'm guessing they moved their API urls?

**Comment by MaZa78** [comment]
I have the same problem. This might be the same issue like it was couple months ago. Token issue.

<img width="425" alt="image" src="https://github.com/skodaconnect/homeassistant-skodaconnect/assets/13133855/2df9107a-433a-481d-afb8-f0f53d5f8596">

**Comment by Farfar** [comment]
Same problem as before, the user agent is soft blocked. A fix is on the way.

**Comment by dvx76** [comment]
Fix https://github.com/skodaconnect/skodaconnect/pull/108

**Comment by kekonn** [comment]
Thanks, that fixed it!
