### ISSUE TITLE
Cannot login anymore in Homeassistant module

### ISSUE THREAD

**Issue by LorDHarA** [skodaconnect/homeassistant-skodaconnect#244]
Hello
Maybe I do something wrong, but it always seemed to work since last week. I wanted to setup the Skoda connect plugin again, but I cannot login anymore and cannot activate Skoda connect in Home assistant. I tried to login in web and android app but no need to accept the license terms or so. Anyone else havbing this problem? I see that Skoda connect app and website has had an upgrade...

Thank you in advance.
<img width="363" alt="skoda" src="https://github.com/skodaconnect/homeassistant-skodaconnect/assets/74097263/722c9479-398c-4a13-ae85-82f9c7344cf1">

**Comment by LorDHarA** [comment]
Some information about my system:
Core 2023.12.1
Supervisor 2023.11.6
Operating System 11.2
Frontend 20231208.2

**Comment by papou-github** [comment]
Same for me: Message in the log : ERROR (MainThread) [skodaconnect.connection] Received unhandled error indicating client-side problem.

**Comment by klausdm** [comment]
Did you update to latest? https://github.com/skodaconnect/homeassistant-skodaconnect/releases/tag/1.2.8

**Comment by Farfar** [comment]
Please check closed issues and updates for integration before opening new issues. Update to latest which contains fix.

**Comment by LorDHarA** [comment]
Hello, I did check for the update, it was not there. When I removed the skoda settings it showed up and installed the update. Sorry to bother, but it was not there yet.. Thank you for you superfast response...

**Comment by klausdm** [comment]
> Hello, I did check for the update, it was not there. When I removed the skoda settings it showed up and installed the update. Sorry to bother, but it was not there yet.. Thank you for you superfast response...

Same here... was not in HACS... had to reboot.
