### ISSUE TITLE
Cannot install main branch through HACS

### ISSUE THREAD

**Issue by ronaldt80** [skodaconnect/homeassistant-skodaconnect#252]
For some reason i'm unable to install main branche through hacs. Can you kindly make available a new release involving recent bug fixes? (Or advice how to install develop through hacs?)

![Screenshot_20240107-194532](https://github.com/skodaconnect/homeassistant-skodaconnect/assets/53364332/e758c564-f279-4ff7-b281-7b141ea52c97)

**Comment by dvx76** [comment]
What change/fix are you looking for?

**Comment by ronaldt80** [comment]
The change proposed in #250 - I can change my own code but prefer to stay close to this repo
