### ISSUE TITLE
Homeassistant depreceated function for GPS

### ISSUE THREAD

**Issue by Kilowatt-W** [skodaconnect/homeassistant-skodaconnect#255]
Hi there

got this message from logs :

SOURCE_TYPE_GPS was used from skodaconnect, this is a deprecated constant which will be removed in HA Core 2025.1. Use SourceType.GPS instead, 

Greetings Kilowatt :-)

**Comment by dvx76** [comment]
Duplicate of #249 and #253, fixed in #250
