### ISSUE TITLE
deprecated constant

### ISSUE THREAD

**Issue by martin346456** [skodaconnect/homeassistant-skodaconnect#258]
SOURCE_TYPE_GPS was used from skodaconnect, this is a deprecated constant which will be removed in HA Core 2025.1. Use SourceType.GPS instead.

**Comment by dvx76** [comment]
Duplicate https://github.com/skodaconnect/homeassistant-skodaconnect/issues/255 https://github.com/skodaconnect/homeassistant-skodaconnect/issues/249 https://github.com/skodaconnect/homeassistant-skodaconnect/issues/253, fixed in https://github.com/skodaconnect/homeassistant-skodaconnect/pull/250
