### ISSUE TITLE
last_connected does not include timezone information

### ISSUE THREAD

**Issue by olant** [skodaconnect/homeassistant-skodaconnect#260]
**Describe the bug**
The integration returns "sensor.antwerpenyaq_last_connected" as "2024-02-04T10:40:37" without a trailing "Z" describing it as UTC.

**Is this working in MySkoda app?***
Not related

**Latest working release**
Never changed for me.

**Debug logs**
Not applicable.

**Installation:**
 - Home Assistant variant: Docker
 - Python version 3.11.6
 - Python library versions

**Additional context**
This makes it hard to do operations with the timestam as all functions rely on valid timezone information.

**Comment by olant** [comment]
I just read the discussion in https://github.com/skodaconnect/skodaconnect/pull/109
This is clearly the reason. I just pulled vehicle.py from theat PR and now the timestamp includes TZ information.

Maybe you want to consider to re-apply that PR in future.

**Comment by dvx76** [comment]
Makes sense. New PR = https://github.com/skodaconnect/skodaconnect/pull/116

**Comment by dvx76** [comment]
Fixed in https://github.com/skodaconnect/skodaconnect/pull/116
