### ISSUE TITLE
Seat-Heating state wrong?!?

### ISSUE THREAD

**Issue by georgbachmann** [skodaconnect/homeassistant-skodaconnect#263]
I am trying out this integration for my Skoda Enyaq 2023.
One problem I found was that the switch.skoda_enyaq_seat_heating_front_left and right is marked as "on" even though it's not. I am currently not heating anything in my car. When i flip the switches it seems to really do something. So it's a bit bad that I don't know it it's doing something or not. Like I don't know the exact state it's really in.

<img width="341" alt="Bildschirmfoto 2024-02-07 um 17 48 16" src="https://github.com/skodaconnect/homeassistant-skodaconnect/assets/893113/df0a4788-3fb0-4b27-bcf1-1ab10a07cadf">

**Is this working in MySkoda app?***
There is no such option in the MySkoda app? Or am I blind? I can only preheat the whole car.

**Latest working release**
Not sure. I discovered this integration a week ago...

**Debug logs**
I added logging today. Will update when I see something relevant in there

**Installation:**
 - Home Assistant variant: Hass OS on Raspberry @ 2024.1.5

**Comment by dvx76** [comment]
Those switches determine if the respective seats will be heated when climate control is turned on.

**Comment by dvx76** [comment]
Equivalent view from the app: ![image](https://github.com/skodaconnect/homeassistant-skodaconnect/assets/785424/f5f5bba3-02b7-48e1-9aec-7255c4d56341)

**Comment by georgbachmann** [comment]
Ahhhhhh!!!! Thank you very much for clarification!!! Cool! Thanks!
