### ISSUE TITLE
Trunck lid status

### ISSUE THREAD

**Issue by 1cgtester** [skodaconnect/homeassistant-skodaconnect#265]
Hi , 

Thx to invest so much energy into skodaconnect.

I can see the status of the windows or doors but I miss the status of the trunk lid....

is this possible to bring this into HA?

best regards

**Comment by 1cgtester** [comment]
Hi,
its an octavia from 2023

but i don`t have the "Trunk" icon, only the hole other things whitch can be closed :-)
![No_trunk1](https://github.com/skodaconnect/homeassistant-skodaconnect/assets/93335238/505960a5-b637-43a2-aae2-c6895f73434c)
![No_trunk2](https://github.com/skodaconnect/homeassistant-skodaconnect/assets/93335238/1012064a-a4a9-4364-b239-080ef6332a31)

**Comment by dvx76** [comment]
Ok. But in the Skoda App you can see the open/closed of the trunk? Just want to make sure it's actually exposed by the Skoda API.

**Comment by 1cgtester** [comment]
the Skoda connect doesn`t show it right.
![No_trunk4](https://github.com/skodaconnect/homeassistant-skodaconnect/assets/93335238/99bba99e-7756-44a6-9e16-c87462e36ee3)

but in the dashboard it looks fine:
![No_trunk3](https://github.com/skodaconnect/homeassistant-skodaconnect/assets/93335238/c2a34735-b35f-48d2-b254-783020fd514f)

so propably Skoda must update the API , right?

**Comment by dvx76** [comment]
The dashboard likely just read the status from the local canbus of the car.

If the Skoda App itself doesn't show the info then I'm afraid you're out of luck.

The integration does seem to have code which tries to read out the trunk open/closed status from the API response: https://github.com/skodaconnect/skodaconnect/blob/bc9371520bf329e6f039844bf1ab92783d3c4ecb/skodaconnect/vehicle.py#L2806

**Comment by 1cgtester** [comment]
Hi,
so let`s wait for an skoda Connect App update...

thank`s a lot
