### ISSUE TITLE
Skoda Connect - Integration Setup - Problem - Login to Skoda Connect fails

### ISSUE THREAD

**Issue by pradez0** [skodaconnect/homeassistant-skodaconnect#267]
Home Assistant:
Core 2024.2.3
Supervisor 2024.02.0
Operating System 11.5
Frontend 20240207.1

After installation of the intergation (Skoda Connect V 1.2.9) via HACS during inital configuration:

After entering the credentials for Skoda Connect in the first dialog box (Account Information) the following error message appears:

"Could not login to Skoda Connect, please check your credentials and verify that the service is working"

The credentials work with the MySkoda (V 7.0.0) app on my Android 13 Smartphone as well as when login in to https://www.skoda-connect.com.

I'd appreciate any help in solving this problem.

Thank you.

**Comment by dvx76** [comment]
This is almost always due to lack of consent with Skoda's end user license agreement, which the newer App somehow bypasses. Typically solved by logging in once using the old "MySkoda Essentials" app.

Your HA logs at the time of receiving the error in the UI would also help confirm this is the problem or not.

**Comment by pradez0** [comment]
Thank you for your quick answer, that solved the problem.
Downloaded the "MySkoda Essentials" App, logged out of the "MySkoda" App, logged in "My Skoda Essentials" and accepted what ever I could find to accept. Was not much, as I had accepted already all the stuff in the "MySkoda" App.
Run the inital configuration of the Skoda Connect integration and did not hit any problem anymore.
Thank you again.
