### ISSUE TITLE
Odometer sensor is unavailable for my Superb iV MJ. 2019

### ISSUE THREAD

**Issue by Headkillah** [skodaconnect/homeassistant-skodaconnect#269]
**Please search issues **
I have, the same bug is posted in Report #124 but was closed as completed in 2022.

**Describe the bug**
@Farfar I have an Superb Sportline iV MJ 2019. I have the problem that the odometer sensor isn´t showing any data (sensor unavailable), no matter wich version from the integration i´m using.

**Is this working in MySkoda app?***
YES, the official "MySkoda" App shows the mileage i´ve droven.

**Latest working release**
The problem exists since first installation last year.

**Debug logs**
No logging for this issue.

**Installation:**
Current Version 2024.3.0
Docker Hub 2024.3.1
Home Assistant Versions 2024.3.1
Python Package Index (PyPI) 2024.3.1

**Additional context**
All other sensors, binary sensors and switches are working perfectly.

Car details:
Škoda Superb Combi Sportline
Firmware: 2019-10-07

**Comment by dvx76** [comment]
Please provide debug logs of one collection cycle where the other sensors are getting refreshed but the odo is not. See https://github.com/skodaconnect/homeassistant-skodaconnect?tab=readme-ov-file#configuration-options and https://github.com/skodaconnect/homeassistant-skodaconnect?tab=readme-ov-file#enable-debug-logging for info wrt debug.

**Comment by Headkillah** [comment]
I´m stupid, it was mine problem. I have not activated the sensor for monitoring the odometer. Thanks anyway, my problem is solved now :)
