### ISSUE TITLE
API and Android APPS timeout

### ISSUE THREAD

**Issue by Dejvic** [skodaconnect/homeassistant-skodaconnect#270]
Hello,
recently, around the new year, it started happening to me that around 12:00 every day both the integration into Homeassistance and the mobile application stopped working.

I decided to write to the claim support that the application is not working for me. they passed it on to the developers and they found out that I was using an unofficial application and they have some kind of protection against these integrations deployed on the server.

I tried to ask them to allow external integration but to no avail.
Has anyone encountered this problem? my personal type is that each user has a limited number of API queries and Home assistance has exhausted them by 12:00. Is it possible to somehow limit the number of API requests so that I can test it? Perhaps also the restriction is only applied to the Czech Republic so far.

Thanks

I am attaching an official email statement from the ŠKODA:

> Hello Mr. Chudek,
> 
> MyŠkoda and MyŠKODA Essentials are the only official applications that can be used with Škoda Connect services. By entering login data into any other application, incl. e.g. unofficial integration into the home automation system (Smart Home) violates the terms of Škoda Connect. Therefore, we cannot provide you with further information and we recommend that you only use the MyŠkoda and MyŠKODA Essentials applications. You can find information about your vehicle in the MyŠkoda or MyŠKODA Essentials application.
> 
> Thank you.
> 
> Best regards
> 
> ANTONÍN HRUŠKA
> 
> Service provider for Škoda Auto a.s., VAC/5 – Customer Care, Support Specialist
> 
> Škoda Auto a.s., class Václav Klement 869, Mladá Boleslav II
> 
> 293 01 Mladá Boleslav, Czech Republic
> 
> connectivity.helpdesk@skoda-auto.cz

**Comment by dvx76** [comment]
Yes this is known behavior. You can find similar cases, including similar responses from Skoda support, in the issues. The actual number of API calls per day seems to vary between car models and countries, so we don't know exactly.

You can you increase the poll frequency of the integration to mitigate the problem. See https://github.com/skodaconnect/homeassistant-skodaconnect?tab=readme-ov-file#configuration-options

**Comment by Dejvic** [comment]
Thank you for the quick response.

I will test and post here the ideal settings I find.

I can provide you with the data for the default polling frequency:
Region: Czech Republic
Vehicle: Skoda Octavia IV
Year of manufacture: 2020
Infotainment version: current

**Comment by Dejvic** [comment]
Hi, I'm adding an update.
I performed some tests with a certain polling frequency, and in order for the Home assistance integration to be functional, as well as the application throughout the day, the minimum polling must be increased to 120s.

I hope it helps someone.
