### ISSUE TITLE
Image can't be loaded

### ISSUE THREAD

**Issue by ChristophCaina** [skodaconnect/homeassistant-skodaconnect#276]
After restarting my System, it seems that the images can't be loaded anymore.
All entities are available, except the car-images

![grafik](https://github.com/skodaconnect/homeassistant-skodaconnect/assets/26391061/c74ba00e-ffd8-44b9-8773-cb8cfe16dfbf)
![grafik](https://github.com/skodaconnect/homeassistant-skodaconnect/assets/26391061/de564406-fffd-4cfa-9c90-50bcd8e0a2a5)

After reloading the config, all entities were unavailable - and the following error could be seen in the logs.

```
Logger: homeassistant.components.switch
Quelle: helpers/entity_platform.py:356
Integration: Schalter ([Dokumentation](https://rc.home-assistant.io/integrations/switch), [Probleme](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+switch%22))
Erstmals aufgetreten: 19:45:41 (2 Vorkommnisse)
Zuletzt protokolliert: 19:46:38

Error while setting up skodaconnect platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 356, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/skodaconnect/switch.py", line 25, in async_setup_entry
    data = hass.data[DOMAIN][entry.entry_id][DATA]
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'b9414cf02e2eb912fbb7407fea826e2c'
```

After installing beta 02 from HA 2024.5 - the integration came back, but the images are still not available.

**Comment by dvx76** [comment]
At first sight the debug doesn't seem related to the issue (the image entities are sensors, not switches).

The image issue reminds me of #191 which turned out to be a temporary glitch in the API responses.

**Comment by UnsignedLong** [comment]
I have the same kind of error.
I have two cars configured but there is only one car at a time that'll work. For the not working car I have the same key error as @ChristophCaina for switch, binary_sensor and device_tracker.
If I reload the non working instance it starts working but the other one stops working with the mentioned key errors.

**Comment by UnsignedLong** [comment]
Downgrading the custom component to 1.2.8 solves my issue, bug was introduces in 1.2.9.

**Comment by dvx76** [comment]
FWIW same `KeyError` was seen in #206

**Comment by stickpin** [comment]
I think in [volkswagencarnet](https://github.com/robinostlund/homeassistant-volkswagencarnet) we are hitting the same [issue](https://github.com/robinostlund/homeassistant-volkswagencarnet/issues/614) after HA 2025.5.x.
It's easily reproducible once you have multiple vehicles configured in the integration.
I am trying to find the root cause as well.

**Comment by dvx76** [comment]
Thanks for sharing! I can only test with one car myself. Upgraded to HA 2024.5.1 and no issue (with one car).

**Comment by dvx76** [comment]
@ChristophCaina do you still have the issue with the model image URL sensors? I can't reproduce. If you still have the problem please look for matching debug logs.

**Comment by ChristophCaina** [comment]
For a couple of days it seems to work now - anyway, I have removed the Image from the Dashboard recently, so I don't see it immediately - If it would fail

**Comment by dvx76** [comment]
Thanks for the update. Please reopen or open a new issue if it happens again and you have logs which suggest it's a client side issue.

**Comment by stickpin** [comment]
@dvx76 just to let you know, I believe you have the same issue as we are in the `volkwagencarnet`:

https://github.com/skodaconnect/homeassistant-skodaconnect/blob/dab59668d619debe9f633473855aaf75cc4b6403/custom_components/skodaconnect/__init__.py#L245-L258

The use of `hass.data` by the `components` is happening before it's actually getting assigned.
You need to change the order, see my PR for more details: https://github.com/robinostlund/homeassistant-volkswagencarnet/pull/617

The issue will be visible only if you have more than one vehicle configured in the integration.
