### ISSUE TITLE
MyŠkoda Essentials app and the Škoda Connect portal is shutting down

### ISSUE THREAD

**Issue by AMajland** [skodaconnect/homeassistant-skodaconnect#287]
I got an email from Skoda today telling me that the MyŠkoda Essentials app and the Škoda Connect portal is shutting down.

It will no longer be available from July 2024 !

I don't know whether the api used by this integration is also shutting down or it is only Skoda's own frontends.

My Enayq is supported by the MySkoda App while the Kodiaq from 2019 is not. That is the car is only 5years old so pretty early to cut  support for remote conenction. I've even paid for the service until 2025-06-08

![image](https://github.com/skodaconnect/homeassistant-skodaconnect/assets/97510471/5aad7996-3ad1-4e2d-9b3f-15422a1dc78a)
![image](https://github.com/skodaconnect/homeassistant-skodaconnect/assets/97510471/b851b55a-e40e-48ad-96cb-6145bddc102c)

**Comment by AMajland** [comment]
https://www.skoda.dk/det-digitale-skoda/my-skoda-app << Danish 

MyŠkoda Essentials:  

- eCitigo iV
- Fabia 
- 3. generation of Octavia 
- Karoq/Kodiaq/Superb (produced until  7/2020) 
- Rapid.

**Comment by Thomsen-79** [comment]
I hope not. Im using this integration alot!

**Comment by dvx76** [comment]
Thanks. I think by now everyone has received the same email. I suspect any remaining models only working with Skoda Essentials will become supported by MySkoda by this date.

We can expect the older API endpoints which are only used by the Essentials app and the portal (and this integration) will eventually go away. But who knows...

Some people have started to look at the newer APIs and how the MySkoda app works but this is a lot of work.

**Comment by AMajland** [comment]
> https://www.skoda.dk/det-digitale-skoda/my-skoda-app << Danish
> 
> MyŠkoda Essentials:
> 
> * eCitigo iV
> * Fabia
> * Octavia, Third generation
> * Karoq/Kodiaq/Superb (produced until  7/2020)
> * Rapid.

My 2019 Kodiaq is now available in the new MySkoda App as well
