### ISSUE TITLE
Discontinuity MySkoda Essentials and Skoda Connect Portal

### ISSUE THREAD

**Issue by XalaTheShepard** [skodaconnect/homeassistant-skodaconnect#289]
Dear,

I have just received an e-mail from Skoda that both apps will be discontinued as from July 2024.
Will this integration still be able to function?
Also the area notification and speed notification will be discontinued.

Kind regards,

Robin

**Comment by WoBBeLnl** [comment]
Same here, new app is over year old BTW. https://play.google.com/store/apps/details?id=cz.skodaauto.myskoda

**Comment by requiemmg** [comment]
I very much hope that this integration will still Work with a new API, I have a lot of infos and automations in HA depending on it 😢

**Comment by dvx76** [comment]
Hi,

Most users have now received the same email wrt the Essentials app EOL. We also know that for new vehicles/accounts the Essentials app, and consequently this integration, is already not working.

There are only a few active developers working on this integration but we are aware of this and we are (slowly) working on making the integration compatible with the new MySkoda app/API. There are no timelines and in fact no guarantee we will get this working. Please be patient and do not open new issues reporting the same thing.

**Comment by 1358** [comment]
Maybe an issue should remain open until there is possibly a solution?
