### ISSUE TITLE
Homeassistant skoda custom integration doesnt work anymore. 

### ISSUE THREAD

**Issue by MattiVisti78** [skodaconnect/homeassistant-skodaconnect#299]
**IMPORTANT NOTE**

This integration currently only supports the old Skoda API compatible with the old Skoda Essentials App.

If you are unable to use the Skoda Essentials account the integration will not work for you. This is the case for new vehicles and/or Skoda accounts.

We are aware the Skoda Essentials app is being deprecated and are working on updating the integration to be compatible with the new API / MySkoda app, but this is a major piece of development work.

Please do not open new issues for this.

**Please search issues in https://github.com/skodaconnect/skodaconnect and https://github.com/skodaconnect/homeassistant-skodaconnect for duplicates or fixes before reporting a new issue.**

**Describe the bug**

**Is this working in MySkoda app?***
Logout and login in the MySkoda app, preferably on Android.
Make sure that you have the latest app updates, sometimes there's new consent needed that will only show in latest app version.

**Latest working release**
If the problem started after updating to a new release, please state latest working release.

**Debug logs**
If applicable, add debug logs. See [README](https://github.com/skodaconnect/homeassistant-skodaconnect#enable-debug-logging) on how to enable debug logs with response debugging.

**Installation:**
 - Home Assistant variant: [e.g. Hass OS, Docker, Core, Supervised]
 - Python version [e.g. 3.7, 3.8]
 - Python library versions ["python3 -m pip list"]

**Additional context**

**Comment by dvx76** [comment]
Please read and follow the issue template.
